"""Auto-generated by scripts/generate_client.sh — do not edit."""

SPEC_SHA256 = "349e398b9ed5b330dbe5ada44992bdc70eac543f1b1d367e7aea0ff1a38a5884"
SPEC_VERSION = "1.0.0"
SPEC_GENERATED_AT = "2026-06-22T15:16:35+00:00"
