"""Auto-generated by scripts/generate_client.sh — do not edit."""

SPEC_SHA256 = "bde9df1eecbf3cf30c4440255e5611dd1312b4758b6c9f7214e594d0df5cbcb6"
SPEC_VERSION = "1.0.0"
SPEC_GENERATED_AT = "2026-04-12T00:00:00+00:00"
