"""Auto-generated by scripts/generate_client.sh — do not edit."""

SPEC_SHA256 = "2bfa3607de3861ac35e0b6f1be93c4dcb565d3cf0ff8e22d46e0344deb4f88c0"
SPEC_VERSION = "1.0.0"
SPEC_GENERATED_AT = "2026-07-14T06:09:25+00:00"
