"""Dump and filter the backend OpenAPI spec for unitysvc-sellers SDK codegen.

Run from inside unitysvc/backend with the backend venv:

    .venv/bin/python /tmp/dump_spec.py /path/to/unitysvc-sellers/openapi.json
"""
import json
import re
import sys
import warnings

warnings.filterwarnings("ignore")

import app.main

OUTPUT = sys.argv[1]

spec = app.main.app.openapi()

# ---------------------------------------------------------------------------
# 1. Filter paths to seller-tagged operations only.
# ---------------------------------------------------------------------------
filtered_paths = {}
for path, item in spec["paths"].items():
    ops = {
        method: op
        for method, op in item.items()
        if method in ("get", "post", "put", "patch", "delete")
        and "seller" in (op.get("tags") or [])
    }
    if ops:
        preserved = {
            k: v for k, v in item.items()
            if k not in ("get", "post", "put", "patch", "delete")
        }
        filtered_paths[path] = {**preserved, **ops}
spec["paths"] = filtered_paths

# ---------------------------------------------------------------------------
# 2. Sanitize schema names containing characters that aren't valid Python
#    identifiers. openapi-python-client cannot handle names like
#    ``PriceRuleStatusEnum-Output`` (generated by FastAPI when two distinct
#    enums share a Python class name and one appears in a response body).
#    We rewrite both the schema key and all $ref values pointing to it.
# ---------------------------------------------------------------------------
def sanitize(name: str) -> str:
    return re.sub(r"[^A-Za-z0-9_]", "", name)

renames: dict[str, str] = {}
for name in list(spec["components"]["schemas"].keys()):
    clean = sanitize(name)
    if clean != name:
        renames[name] = clean

for old, new in renames.items():
    spec["components"]["schemas"][new] = spec["components"]["schemas"].pop(old)

def rewrite_refs(obj):
    if isinstance(obj, dict):
        for k, v in list(obj.items()):
            if k == "$ref" and isinstance(v, str) and v.startswith("#/components/schemas/"):
                old = v[len("#/components/schemas/") :]
                if old in renames:
                    obj[k] = f"#/components/schemas/{renames[old]}"
            else:
                rewrite_refs(v)
    elif isinstance(obj, list):
        for item in obj:
            rewrite_refs(item)

rewrite_refs(spec)

# ---------------------------------------------------------------------------
# 3. Strip auto-generated ``title`` from anonymous inline object schemas.
#
#    pydantic v2 auto-derives a JSON Schema ``title`` from a field name
#    (e.g. ``pricing: dict[str, Any]`` -> ``title: "Pricing"``).
#    openapi-python-client uses that title as a class-name hint, so two
#    unrelated models each with a ``pricing: dict`` field collide with
#    "Attempted to generate duplicate models with name Pricing". Stripping
#    the title from anonymous ``type: object`` schemas (no ``properties``,
#    no ``$ref``) lets the generator synthesize unique parent-qualified
#    names instead.
# ---------------------------------------------------------------------------
stripped_titles: list[str] = []


def is_anonymous_object(obj: dict) -> bool:
    if not isinstance(obj, dict):
        return False
    if obj.get("type") != "object":
        return False
    if "$ref" in obj:
        return False
    if "properties" in obj:
        return False
    return True


def strip_inline_titles(obj, path=""):
    if isinstance(obj, dict):
        if is_anonymous_object(obj) and "title" in obj:
            stripped_titles.append(f"{path}: {obj['title']}")
            del obj["title"]
        for k, v in obj.items():
            strip_inline_titles(v, f"{path}.{k}" if path else k)
    elif isinstance(obj, list):
        for i, v in enumerate(obj):
            strip_inline_titles(v, f"{path}[{i}]")


strip_inline_titles(spec)

with open(OUTPUT, "w") as f:
    json.dump(spec, f, indent=2)

# Report
seller_ops = sum(
    1
    for p, i in spec["paths"].items()
    for m, op in i.items()
    if m in ("get", "post", "put", "patch", "delete")
)
print(f"wrote {OUTPUT}")
print(f"  paths: {len(spec['paths'])}  seller ops: {seller_ops}")
if renames:
    print(f"  schema renames ({len(renames)}):")
    for old, new in renames.items():
        print(f"    {old!r} -> {new!r}")
if stripped_titles:
    print(f"  stripped {len(stripped_titles)} inline object titles")
