#!/usr/bin/env bash
# Regenerate docs/cli-reference.md from the live CLI via typer utils docs.
#
# Usage:
#     ./scripts/generate_cli_reference.sh
#
# Requires the project to be installed (uv run handles this automatically).
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="${REPO_ROOT}/docs/cli-reference.md"

HEADER="<!-- Auto-generated by scripts/generate_cli_reference.sh — do not edit by hand. -->
<!-- Regenerate: ./scripts/generate_cli_reference.sh -->

# CLI Reference
"

BODY="$(uv run typer unitysvc_sellers.cli utils docs --name usvc_seller)"

printf '%s\n%s\n' "$HEADER" "$BODY" > "$OUT"
echo "Wrote ${OUT} ($(wc -l < "$OUT") lines)"
